version: '3.9'

services:
  backend:
    container_name: backend
    build: 
      context: backend
      dockerfile: Dockerfile
    image: compose-backend
    ports:
      - 4000:3000
    env_file: 
      - .env

  frontend:
    container_name: frontend
    build: 
      context: frontend
      dockerfile: Dockerfile
    image: compose-frontend
    ports:
      - 8081:80
    env_file: 
      - .env

  postgres:
    container_name: postgres
    image: postgres
    env_file: 
      - .env
    volumes: 
      - bd_postgres:/data/postgres

volumes: 
      bd_postgres:   